-- Faz 6 — expanded RBAC roles (additive enum values)
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'OPS_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'LOGISTICS_OPERATOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FINANCE_OPERATOR';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DOCUMENT_CONTROLLER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FORWARDER';
